Update elpa-admin to 509fc27b85a8
(Latest commit on upstream main branch as of 2026-04-20.)

The previous commit referenced in d89fc0f568eb6b7b2c5353399a254a23f3310a7f
is no longer available upstream!

    warning: redirecting to https://git.savannah.gnu.org/r/emacs/elpa.git/
    error: Unable to find b9cb699723937d37c6739d32aec0f00b85d0fa8f under https://git.savannah.gnu.org/r/emacs/elpa.git
    Cannot obtain needed object b9cb699723937d37c6739d32aec0f00b85d0fa8f
    error: fetch failed.
    fatal: Fetched in submodule path 'lib/elpa-admin', but it did not contain b9cb699723937d37c6739d32aec0f00b85d0fa8f. Direct fetching of that commit failed.